- hosts: 'localhost'
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update pacman cache
      community.general.pacman:
        update_cache: true
      become: true
      tags:
        - dotfiles
        - neovim

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/secrets.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/github.yml
    - include_tasks: tasks/nvim.yml

    - name: Install tmux
      community.general.pacman:
        name: tmux
        state: present
      become: true
      tags:
        - tmux

    - name: Install tmux plugin manager
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: '~/.tmux/plugins/tpm'
      tags:
        - tmux

    - name: Install exa
      community.general.pacman:
        name: exa
        state: present
      become: true
      tags:
        - exa

    - name: Install fzf
      git:
        repo: 'https://github.com/junegunn/fzf.git'
        depth: 1
        dest: '~/.fzf'

    - name: Install fzf bindings
      shell: ~/.fzf/install --completion --key-bindings --no-update-rc

    - name: Install xclip
      community.general.pacman:
        name: xclip
        state: present
      become: true

    # TODO: move this to separate file
    - name: Install nodejs, npm, yarn
      community.general.pacman:
        name: [nodejs, npm, yarn]
        state: present
      become: true

