- hosts: 'localhost'
  become: true
  pre_tasks:
    - name: Update pacman cache
      community.general.pacman:
        update_cache: true
      tags:
        - dotfiles
        - neovim

  tasks:
    - name: Dotfile tasks
      include_tasks: tasks/dotfiles.yml

    - name: Neovim tasks
      include_tasks: tasks/nvim.yml

    - name: Install tmux
      community.general.pacman:
        name: tmux
        state: present
      tags:
        - tmux

    - name: Install tmux plugin manager
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: '~/.tmux/plugins/tpm'
      tags:
        - tmux

    - name: Install exa
      community.general.pacman:
        name: exa
        state: present
      tags:
        - exa

    - name: Install fzf
      git:
        repo: 'https://github.com/junegunn/fzf.git'
        depth: 1
        dest: '~/.fzf'

    - name: Install fzf bindings
      shell: ~/.fzf/install
