- name: Install stow
  community.general.pacman:
    name: stow
    state: present
  tags:
    - dotfiles

- name: Install zsh autosuggestions
  git:
    repo: 'https://github.com/gihook/config-files.git'
    dest: '~/github/config-files'
  tags:
    - dotfiles

- name: Stow tmux
  shell: cd ~/github/config-files && stow --target ~ -S tmux
  tags:
    - dotfiles

- name: Stow nvim
  shell: cd ~/github/config-files && stow --target ~ -S nvim
  tags:
    - dotfiles
