- name: Install stow
  community.general.pacman:
    name: stow
    state: present
  become: true
  tags:
    - dotfiles

- name: Clone dotfiles
  git:
    repo: 'git@github.com:gihook/config-files.git'
    dest: '~/github/config-files'
    accept_hostkey: yes
  tags:
    - dotfiles

- name: Install dotfiles 
  shell: cd ~/github/config-files && ./install.sh
  tags:
    - dotfiles
