- name: Install neovim
  community.general.pacman:
    name: neovim
    state: present
  tags:
    - neovim

- name: Install neovim packer
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: '~/.local/share/nvim/site/pack/packer/start/packer.nvim'
    depth: 1
  tags:
    - neovim

