- name: Ensure secrets directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/secrets"
    mode: 0700
    state: directory
  tags:
    - secrets

- name: Copy passwords.kdbx
  copy:
    src: secrets/passwords.kdbx
    dest: "{{ lookup('env', 'HOME') }}/secrets"
    mode: '0600'
  tags:
    - secrets

- name: Copy environment-variables
  copy:
    src: secrets/environment-variables
    dest: "{{ lookup('env', 'HOME') }}/secrets"
    mode: '0600'
  tags:
    - secrets

- name: Install keepassxc
  community.general.pacman:
    name: keepassxc
    state: present
  become: true
  tags:
    - secrets
