- name: Ensure secrets directory exists
  file:
    dest: ~/secrets
    mode: 0700
    state: directory

- name: Copy secrets
  copy:
    src: secrets/passwords.kdbx
    dest: ~/secrets
    mode: '0600'
