- name: Ensure secrets directory exists
  file:
    dest: ~/secrets
    mode: 0700
    state: directory
  tags:
    - secrets

- name: Copy secrets
  copy:
    src: secrets/passwords.kdbx
    dest: ~/secrets
    mode: '0600'
  tags:
    - secrets

- name: Install keepassxc
  community.general.pacman:
    name: keepassxc
    state: present
  tags:
    - secrets
