- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install ssh key
  copy: 
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Install ssh public key
  copy: 
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh

- name: Install work ssh key
  copy: 
    src: "./.ssh/work_id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/work_id_rsa"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install work ssh public key
  copy: 
    src: "./.ssh/work_id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/work_id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh
